name: Docker Image CI

on:
  workflow_dispatch:
  #push:
  #  branches: ["freeproject"]
  #pull_request:
  #  branches: ["freeproject"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "**/appsettings.Production.json"
        env:
          ConnectionStrings.FreeProject: ${{ secrets.SQLCONNECTIONSTRING }}
          Jwt.Key: ${{ secrets.JWTKEY }}
          Jwt.Issuer: ${{ secrets.JWTISSUER }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: zafry26/freeproject

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
